// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Finder is an autogenerated mock type for the Finder type
type Finder struct {
	mock.Mock
}

// Find provides a mock function with given fields: num
func (_m *Finder) Find(num int) error {
	ret := _m.Called(num)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(num)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
